version: '3'

volumes:
  enroller_pg_data:
  devices_pg_data:

services:
  enrollerdb:
    build:
      context: https://github.com/lamassuiot/enroller.git#main
      dockerfile: Dockerfile.enrollerdb
    environment:
      POSTGRES_DB: enroller
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports: 
      - 5432:5432
    volumes:
      - 'enroller_pg_data:/var/lib/postgresql/data'

  devicesdb:
    build:
      context: .
      dockerfile: Dockerfile.devicesdb
    environment:
      POSTGRES_DB: devices
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - 'devices_pg_data:/var/lib/postgresql/data'
    ports: 
      - 5433:5432